[package]
name = "YotferTele"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
pretty_env_logger = "0.5.0"
serde = "1.0.219"
serde_json = "1.0.142"
teloxide = "0.17.0"

tokio.workspace = true 
